
-- day 2
-- question link https://drive.google.com/file/d/1dejJEaPdP5OGm1hxujtC5kHlQe9eg8Nf/view


-- Practice Set 1 — Basics + CRUD + Filtering
-- Scenario: Restaurant Menu
CREATE DATABASE sql_practice_pack;
USE sql_practice_pack;
CREATE TABLE menu_items (
item_id INT PRIMARY KEY,
item_name VARCHAR(100),
category VARCHAR(50),
price DECIMAL(10,2),
available_qty INT
);
INSERT INTO menu_items VALUES
(1, 'Chicken Biryani', 'Main Course', 320, 25),
(2, 'Paneer Tikka', 'Starter', 240, 15),
(3, 'Masala Dosa', 'Breakfast', 120, 30),
(4, 'Veg Burger', 'Fast Food', 180, 10),
(5, 'Cold Coffee', 'Beverage', 150, 20),
(6, 'Chicken Burger', 'Fast Food', 220, 8),
(7, 'Idli', 'Breakfast', 80, 40),
(8, 'Fresh Lime', 'Beverage', 90, 0);
/*
Exercises

1. Display all menu items.
2. Display only item name and price.
3. Add a new menu item.
4. Change the price of Chicken Biryani .
5. Increase the price of all Fast Food products by 10%.
6. Reduce the available quantity of Veg Burger by 2.
7. Delete products whose available quantity is 0.
8. Display items costing more than ₹200.
9. Display items priced between ₹100 and ₹250.
10. Display all Breakfast items.

11. Display items belonging to Breakfast or Beverage.
12. Display products whose names contain Chicken .
13. Sort items from highest price to lowest.
14. Display the three most expensive items.
15. Display products where available quantity is less than 15.*/
SELECT * from menu_items;
SELECT item_name,price from menu_items;
INSERT INTO menu_items VALUES(9,'Fried Rice','Main Course',200,10);
UPDATE menu_items SET price= 300 where item_name='Chicken Biryani';
UPDATE menu_items SET price= (price*1.1) where category='Fast Food';
UPDATE menu_items SET available_qty= (available_qty-2) where item_name='Veg Burger';
DELETE FROM menu_items WHERE available_qty=0;
SELECT item_name,price from menu_items where price>200;
SELECT item_name,price from menu_items where price BETWEEN 100 AND 250;
SELECT * from menu_items where category='Breakfast';
SELECT * from menu_items where category ='Breakfast' OR category= 'Beverage';
SELECT * from menu_items WHERE item_name LIKE '%Chicken%';
SELECT * FROM menu_items ORDER BY price desc;
SELECT * FROM menu_items ORDER BY price desc limit 3;
SELECT * FROM menu_items WHERE available_qty<15;

-- Practice Set 2 — Aggregate Functions + GROUP BY + HAVING
-- Scenario: Food Delivery Orders
CREATE TABLE food_orders (
order_id INT PRIMARY KEY,
restaurant VARCHAR(100),
city VARCHAR(50),
food_type VARCHAR(50),
order_amount DECIMAL(10,2),
delivery_partner VARCHAR(50),
order_date DATE
);
INSERT INTO food_orders VALUES
(101, 'Spice Hub', 'Hyderabad', 'Indian', 850, 'Ravi', '2026-09-01'),
(102, 'Burger Zone', 'Hyderabad', 'Fast Food', 520, 'Kiran', '2026-09-01'),
(103, 'Pizza Point', 'Mumbai', 'Fast Food', 1100, 'Ravi', '2026-09-02'),
(104, 'Curry House', 'Bangalore', 'Indian', 760, 'Aman', '2026-09-02'),
(105, 'Spice Hub', 'Hyderabad', 'Indian', 1250, 'Kiran', '2026-09-03'),
(106, 'Sushi World', 'Mumbai', 'Japanese', 1800, 'Aman', '2026-09-03'),
(107, 'Pizza Point', 'Mumbai', 'Fast Food', 900, 'Ravi', '2026-09-04'),
(108, 'Curry House', 'Bangalore', 'Indian', 640, 'Kiran', '2026-09-04'),
(109, 'Burger Zone', 'Hyderabad', 'Fast Food', 430, 'Aman', '2026-09-05'),
(110, 'Sushi World', 'Mumbai', 'Japanese', 2100, 'Ravi', '2026-09-05'),
(111, 'Spice Hub', 'Hyderabad', 'Indian', 950, 'Aman', '2026-09-06'),
(112, 'Curry House', 'Bangalore', 'Indian', 880, 'Ravi', '2026-09-06');

/*Exercises

1. Find the total number of orders.
2. Find total revenue.
3. Find average order value.
4. Find highest order amount.
5. Find lowest order amount.
6. Find total revenue by city.
7. Find number of orders by restaurant.
8. Find average order value by food type.
9. Find total revenue generated by each delivery partner.
10. Find cities having more than 3 orders.
11. Find restaurants generating more than ₹2,000 revenue.
12. Find delivery partners whose average order amount exceeds ₹800.
13. Find food types whose total revenue exceeds ₹2,500.
14. Display city-wise revenue from highest to lowest.
15. Find the top-performing restaurant based on revenue.*/

SELECT COUNT(order_id) from food_orders;
SELECT SUM(order_amount) from food_orders;
SELECT AVG(order_amount) from food_orders;
SELECT MAX(order_amount) from food_orders;
SELECT MIN(order_amount) from food_orders;
SELECT city,sum(order_amount) from food_orders GROUP by city;
SELECT restaurant,count(order_id) from food_orders GROUP by restaurant;
SELECT food_type,count(order_id) from food_orders GROUP by food_type;
SELECT delivery_partner,sum(order_amount) from food_orders GROUP by delivery_partner;
SELECT city,count(order_id) as total from food_orders GROUP by city HAVING total>3;
SELECT restaurant,sum(order_amount) as total from food_orders GROUP by restaurant HAVING total>2000;
SELECT delivery_partner,avg(order_amount) as avge from food_orders GROUP by delivery_partner HAVING avge>800;
SELECT food_type,sum(order_amount) as avge from food_orders GROUP by food_type HAVING avge>2500;
SELECT city,sum(order_amount) as tot from food_orders GROUP by city ORDER BY tot desc;
SELECT restaurant,sum(order_amount) as revenue from food_orders GROUP by restaurant ORDER BY revenue desc limit 1;


-- Practice Set 3 — JOIN Practice
-- Scenario: Training Institute

CREATE TABLE students (
student_id INT PRIMARY KEY,
student_name VARCHAR(100),
city VARCHAR(50)
);
INSERT INTO students VALUES
(1, 'Arun', 'Hyderabad'),
(2, 'Megha', 'Mumbai'),
(3, 'Zaid', 'Hyderabad'),
(4, 'Pooja', 'Pune'),
(5, 'Rohan', 'Delhi'),
(6, 'Sana', NULL),
(7, 'Vijay', 'Bangalore');

CREATE TABLE courses (
course_id INT PRIMARY KEY,
course_name VARCHAR(100),
fee DECIMAL(10,2)
);

INSERT INTO courses VALUES
(101, 'Python', 15000),
(102, 'Data Engineering', 25000),
(103, 'Power BI', 12000),
(104, 'Cloud Computing', 20000),
(105, 'Cyber Security', 22000),
(106, 'Machine Learning', 28000);

CREATE TABLE enrollments (
enrollment_id INT PRIMARY KEY,
student_id INT,
course_id INT,
enrollment_date DATE
);
INSERT INTO enrollments VALUES
(1001, 1, 101, '2026-09-01'),
(1002, 1, 102, '2026-09-03'),
(1003, 2, 103, '2026-09-04'),
(1004, 3, 102, '2026-09-05'),
(1005, 4, 104, '2026-09-06'),
(1006, 2, 101, '2026-09-07'),
(1007, 3, 105, '2026-09-08'),
(1008, 20, 102, '2026-09-09'),
(1009, 5, NULL, '2026-09-10');

/*Exercises

1. Display student name and course name.
2. Display student name, city, course name and fee.
3. Find students enrolled in Data Engineering .
4. Display all students including those having no enrollment.
5. Find students who have never enrolled in a course.
6. Display all courses including courses having no students.
7. Find courses having no enrollments.
8. Identify enrollment records having no valid student.
9. Identify enrollment records having no valid course.
10. Find total courses taken by each student.
11. Find total fees associated with each student's enrollments.
12. Find students enrolled in more than one course.
13. Find courses having more than one student.

14. Find total enrollment revenue by course.
15. Display the course generating the highest enrollment revenue.
*/

SELECT s.student_name,c.course_name FROM enrollments e 
INNER join students s on e.student_id=s.student_id
INNER JOIN courses c on e.course_id=c.course_id;

SELECT s.student_name,s.city,c.course_name,c.fee FROM enrollments e 
INNER join students s on e.student_id=s.student_id
INNER JOIN courses c on e.course_id=c.course_id;

SELECT s.student_name,s.city FROM enrollments e 
INNER join students s on e.student_id=s.student_id 
INNER JOIN courses c on e.course_id=c.course_id where c.course_name='Data Engineering';

SELECT * from students s left join enrollments e on s.student_id=e.student_id;

SELECT * from students s left join enrollments e on s.student_id=e.student_id where e.enrollment_id is NULL;

SELECT * FROM enrollments e 
RIGHT join courses c on e.course_id=c.course_id;

SELECT * FROM enrollments e 
RIGHT join courses c on e.course_id=c.course_id where e.enrollment_id is null;

SELECT * from enrollments e left join students s on s.student_id=e.student_id where s.student_id is null;

SELECT * from enrollments e left join courses c on c.course_id=e.course_id where c.course_id is null;

SELECT s.student_name,count(distinct e.course_id) from enrollments e right join students s on e.student_id=s.student_id GROUP by s.student_id ;

SELECT s.student_name,COALESCE(sum(c.fee),0) from students s left join enrollments e on e.student_id=s.student_id
left JOIN courses c on c.course_id=e.course_id GROUP by s.student_id ; -- to convert null to 0 we use coalesce

SELECT s.student_name,count(distinct e.course_id) as tot from enrollments e inner join students s on e.student_id=s.student_id GROUP by s.student_id having tot>1;

SELECT c.course_name,count(distinct e.student_id) as tot from enrollments e inner join courses c on e.course_id=c.course_id GROUP by c.course_id having tot>1;

SELECT c.course_name,sum( c.fee) as tot from enrollments e inner join courses c on e.course_id=c.course_id GROUP by c.course_id ;

SELECT c.course_name,sum( c.fee) as tot from enrollments e inner join courses c on e.course_id=c.course_id WHERE e.enrollment_id is not null GROUP by c.course_id order by tot desc limit 1;


-- Practice Set 4 — Stored Procedures

-- Scenario: Vehicle Rental

CREATE TABLE vehicles (
vehicle_id INT PRIMARY KEY,
vehicle_name VARCHAR(100),
vehicle_type VARCHAR(50),
daily_rate DECIMAL(10,2),
available_status VARCHAR(20)
);
INSERT INTO vehicles VALUES
(1, 'Honda City', 'Car', 2500, 'Available'),
(2, 'Toyota Innova', 'Car', 3500, 'Available'),
(3, 'Royal Enfield', 'Bike', 1200, 'Rented'),
(4, 'Activa', 'Scooter', 700, 'Available'),
(5, 'Mahindra Thar', 'SUV', 4500, 'Rented'),
(6, 'Hyundai Creta', 'SUV', 3200, 'Available'),
(7, 'KTM Duke', 'Bike', 1500, 'Available');
SELECT * from vehicles;
/* Stored Procedure Exercises

1. Create GetAllVehicles .
2. Create GetAvailableVehicles .
3. Create a procedure accepting vehicle type and returning matching vehicles.
4. Create a procedure accepting maximum daily rate.
5. Create a procedure accepting vehicle ID and new daily rate.
6. Create a procedure to change vehicle status.
7. Create a procedure that increases the daily rate by a supplied percentage.
8. Create a procedure that deletes a vehicle based on vehicle ID.
9. Create a procedure returning all vehicles between two rental rates.
10. Create a procedure that counts vehicles based on vehicle type.
*/
delimiter $$
create procedure GetAllVehicles()
BEGIN
    SELECT * FROM vehicles;
END$$
delimiter ;
call GetAllVehicles();

delimiter $$
create procedure GetAvailableVehicles()
BEGIN
    SELECT * FROM vehicles where available_status='Available';
END$$
delimiter ;
call GetAvailableVehicles();

delimiter $$
create procedure GetVehiclesByType(in veh_type VARCHAR(100))
BEGIN
    SELECT * FROM vehicles where vehicle_type=veh_type;
END$$
delimiter ;
call GetVehiclesByType('Car');

delimiter $$
create procedure MaxDailyRate(in n_rate DECIMAL(10,2))
BEGIN
    SELECT * FROM vehicles where daily_rate<=n_rate;
END$$
delimiter ;
call MaxDailyRate(1200);

delimiter $$
create procedure NewRate(in n_id int ,in n_rate DECIMAL(10,2))
BEGIN
    UPDATE vehicles set daily_rate=n_rate where vehicle_id=n_id;
END$$
delimiter ;
call NewRate(1,1200);

DELIMITER $$
CREATE PROCEDURE UpdateStatus(
    IN n_id INT,
    IN n_status VARCHAR(20)
)
BEGIN
    UPDATE vehicles
    SET available_status = n_status
    WHERE vehicle_id = n_id;
END$$
DELIMITER ;
CALL UpdateStatus(4, 'Available');

DELIMITER $$
CREATE PROCEDURE IncByPercent(
    IN n_per DECIMAL(10,2)
)
BEGIN
    UPDATE vehicles
    SET daily_rate = daily_rate + (daily_rate * n_per / 100);
END$$
DELIMITER ;
CALL IncByPercent(10);

delimiter $$
create procedure DelByID(in n_id INT)
BEGIN
    DELETE from vehicles where vehicle_id=n_id;
END$$
delimiter ;
call DelByID(1)

delimiter $$
create procedure ReturnBetw(in n_id1 DECIMAL(10,2),in n_id2 DECIMAL(10,2))
BEGIN
    SELECT * from vehicles where daily_rate BETWEEN n_id1 and n_id2;
END$$
delimiter ;
call ReturnBetw(700,2000)

delimiter $$
create procedure TypeCount()
BEGIN
    SELECT count(vehicle_id) as tot,vehicle_type from vehicles GROUP by vehicle_type;
END$$
delimiter ;
call TypeCount();


-- Practice Set 5 — Data Cleansing + RegEx
/*TRIM() — remove unwanted spaces
UPPER() — convert to uppercase
LOWER() — convert to lowercase
Finding blank emails- WHERE email = ''
REPLACE() — remove characters
REPLACE(column, old_value, new_value)
Regular Expression (RegEx) is a pattern used to identify text.
Think of it as a rule for recognizing characters.
REGEXP_REPLACE(mobile, '[^0-9]', '')
Meaning:
Find every character that is NOT a number and replace it with nothing.
REGEXP_LIKE()
To test whether a value matches a pattern:
REGEXP_LIKE(email, 'pattern')
CASE
    WHEN condition THEN result
    ELSE result
END
*/
-- Scenario: Online Registration Data

CREATE TABLE registrations (
registration_id INT PRIMARY KEY,
full_name VARCHAR(100),
email VARCHAR(100),
mobile VARCHAR(40),
city VARCHAR(50),
postal_code VARCHAR(20)
);
INSERT INTO registrations VALUES
(1, ' rohit sharma ', ' ROHIT@GMAIL.COM ', '+91-98765-43210', 'hyderabad','568723'),
(2, 'SARA KHAN', 'sara@yahoo.com', '99887 66554', ' MUMBAI ', '400001'),
(3, ' amit patel ', '', '(040)99887766', 'Hyderabad', '500 032'),
(4, 'Neha Singh ', NULL, '9876543210', 'BANGALORE', '560001'),
(5, 'imran ali', 'IMRAN@MAIL.COM ', '91 9988772211', NULL, '500084'),
(6, 'Priya Rao', 'priya@gmail', '98765-AB210', 'Pune', '411001');

/*Exercises

1. Remove spaces before and after names.
2. Convert names to uppercase.
3. Convert email addresses to lowercase.
4. Convert blank email values into NULL .
5. Remove spaces and hyphens from mobile numbers.
6. Remove every non-numeric character from mobile numbers.
7. Standardize city names to uppercase.
8. Find records where city is NULL .
9. Find records where email is NULL or blank.
10. Find only Gmail email addresses using RegEx.
11. Identify incorrectly formatted email addresses.
12. Extract only numeric characters from postal codes.
13. Find mobile numbers containing alphabetic characters.
14. Produce a cleaned output containing name, email, mobile and city.
15. Create a cleaned copy of the data in another table.
*/
SELECT TRIM(full_name) AS cleaned_name
FROM registrations;
SELECT UPPER(TRIM(full_name)) AS cleaned_name
FROM registrations;
SELECT LOWER(TRIM(email)) AS cleaned_email
FROM registrations;
SELECT
    CASE
        WHEN TRIM(email) = '' THEN NULL
        ELSE email
    END AS cleaned_email
FROM registrations;
SELECT
    REPLACE(
        REPLACE(mobile, ' ', ''),
        '-',
        ''
    ) AS cleaned_mobile
FROM registrations;
SELECT
    REGEXP_REPLACE(mobile, '[^0-9]', '') AS cleaned_mobile
FROM registrations;
SELECT
    UPPER(TRIM(city)) AS cleaned_city
FROM registrations;
SELECT *
FROM registrations
WHERE city IS NULL;
SELECT *
FROM registrations
WHERE email IS NULL
   OR email = '';
SELECT *
FROM registrations
WHERE REGEXP_LIKE(
    LOWER(TRIM(email)),
    '^[^@]+@gmail\.com$'
);
SELECT *
FROM registrations
WHERE email IS NOT NULL
  AND TRIM(email) <> ''
  AND NOT REGEXP_LIKE(
      TRIM(email),
      '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'
  );
SELECT
    REGEXP_REPLACE(postal_code, '[^0-9]', '') AS cleaned_postal_code
FROM registrations;
SELECT *
FROM registrations
WHERE REGEXP_LIKE(mobile, '[A-Za-z]');
SELECT
    UPPER(TRIM(full_name)) AS name,

    CASE
        WHEN TRIM(email) = '' THEN NULL
        ELSE LOWER(TRIM(email))
    END AS email,

    REGEXP_REPLACE(mobile, '[^0-9]', '') AS mobile,

    UPPER(TRIM(city)) AS city

FROM registrations;
CREATE TABLE cleaned_registrations AS
SELECT
    registration_id,

    UPPER(TRIM(full_name)) AS full_name,

    CASE
        WHEN TRIM(email) = '' THEN NULL
        ELSE LOWER(TRIM(email))
    END AS email,

    REGEXP_REPLACE(mobile, '[^0-9]', '') AS mobile,

    UPPER(TRIM(city)) AS city,

    REGEXP_REPLACE(postal_code, '[^0-9]', '') AS postal_code

FROM registrations;

SELECT *
FROM cleaned_registrations;

-- Practice Set 6 — Analytical Functions + OVER +PARTITION BY
-- Scenario: Call Centre Performance
/*
Don't confuse these:

GROUP BY
SELECT team, AVG(calls_handled)
FROM call_performance
GROUP BY team;

Output: one row per team.

Window function
SELECT
    agent_name,
    team,
    calls_handled,
    AVG(calls_handled) OVER(
        PARTITION BY team
    ) AS team_average
FROM call_performance;

Output: all original rows + team average.

That's essentially the reason analytical/window functions exist.
FUNCTION() OVER(
    PARTITION BY ...
    ORDER BY ...
)

Not every function needs every part.

Entire table
SUM(calls_handled) OVER()
Per team
SUM(calls_handled) OVER(
    PARTITION BY team
)
Per agent
SUM(calls_handled) OVER(
    PARTITION BY agent_name
)
Running total per agent
SUM(calls_handled) OVER(
    PARTITION BY agent_name
    ORDER BY performance_date
)
Previous value
LAG(calls_handled) OVER(
    PARTITION BY agent_name
    ORDER BY performance_date
)
Average per team
AVG(calls_handled) OVER(
    PARTITION BY team
)*/
CREATE TABLE call_performance (
call_id INT PRIMARY KEY,
agent_name VARCHAR(100),
team VARCHAR(50),
calls_handled INT,
customer_rating DECIMAL(3,2),
performance_date DATE
);
INSERT INTO call_performance VALUES
(1, 'Aman', 'Alpha', 42, 4.50, '2026-09-01'),
(2, 'Sara', 'Alpha', 38, 4.70, '2026-09-01'),
(3, 'Ravi', 'Beta', 50, 4.20, '2026-09-01'),
(4, 'Neha', 'Beta', 45, 4.80, '2026-09-01'),
(5, 'Aman', 'Alpha', 48, 4.60, '2026-09-02'),
(6, 'Sara', 'Alpha', 44, 4.50, '2026-09-02'),
(7, 'Ravi', 'Beta', 46, 4.30, '2026-09-02'),
(8, 'Neha', 'Beta', 52, 4.90, '2026-09-02'),
(9, 'Kabir', 'Alpha', 41, 4.40, '2026-09-01'),
(10, 'Kabir', 'Alpha', 49, 4.60, '2026-09-02'),
(11, 'Pooja', 'Beta', 45, 4.70, '2026-09-01'),
(12, 'Pooja', 'Beta', 50, 4.80, '2026-09-02');

/*Exercises

1. Display each row along with total calls handled across the entire table.
2. Display each row along with total calls handled by its team.
3. Display each agent's record along with average calls handled by the team.
4. Display each row along with team average customer rating.
5. Find cumulative calls handled by each agent ordered by date.
6. Calculate cumulative calls at the team level.
7. Compare each row's calls with the team's average calls.
8. Display the previous day's call count for each agent.

9. Calculate the difference between current and previous call count.
10. Display total calls handled by each agent without collapsing rows.*/

SELECT
    call_id,
    agent_name,
    team,
    calls_handled,
    SUM(calls_handled) OVER() AS total_calls
FROM call_performance;

SELECT
    call_id,
    agent_name,
    team,
    calls_handled,
    SUM(calls_handled) OVER(
        PARTITION BY team
    ) AS team_total_calls
FROM call_performance;

SELECT
    call_id,
    agent_name,
    team,
    calls_handled,
    AVG(calls_handled) OVER(
        PARTITION BY team
    ) AS team_avg_calls
FROM call_performance;

SELECT
    call_id,
    agent_name,
    team,
    customer_rating,
    AVG(customer_rating) OVER(
        PARTITION BY team
    ) AS team_avg_rating
FROM call_performance;

SELECT
    call_id,
    agent_name,
    performance_date,
    calls_handled,
    SUM(calls_handled) OVER(
        PARTITION BY agent_name
        ORDER BY performance_date
    ) AS cumulative_calls
FROM call_performance;

SELECT
    call_id,
    agent_name,
    team,
    performance_date,
    calls_handled,
    SUM(calls_handled) OVER(
        PARTITION BY team
        ORDER BY performance_date, call_id
    ) AS cumulative_team_calls
FROM call_performance;

SELECT
    call_id,
    agent_name,
    team,
    calls_handled,
    AVG(calls_handled) OVER(
        PARTITION BY team
    ) AS team_avg_calls,
    calls_handled -
    AVG(calls_handled) OVER(
        PARTITION BY team
    ) AS difference_from_team_avg
FROM call_performance;

SELECT
    call_id,
    agent_name,
    performance_date,
    calls_handled,
    LAG(calls_handled) OVER(
        PARTITION BY agent_name
        ORDER BY performance_date
    ) AS previous_calls
FROM call_performance;

SELECT
    call_id,
    agent_name,
    performance_date,
    calls_handled,
    LAG(calls_handled) OVER(
        PARTITION BY agent_name
        ORDER BY performance_date
    ) AS previous_calls,
    calls_handled -
    LAG(calls_handled) OVER(
        PARTITION BY agent_name
        ORDER BY performance_date
    ) AS call_difference
FROM call_performance;

SELECT
    call_id,
    agent_name,
    performance_date,
    calls_handled,
    SUM(calls_handled) OVER(
        PARTITION BY agent_name
    ) AS agent_total_calls
FROM call_performance;

-- Practice Set 7 — Ranking

-- Use the same call_performance table.
/*
Simple rule

ROW_NUMBER

Everyone gets a different number.

RANK

Same values get the same rank, and gaps are created.

DENSE_RANK

Same values get the same rank, but no gaps.
Why are these called Window Functions?
it creates the window over which SQL performs the calculation

FUNCTION() OVER(...)

ask three questions.

Question 1 — What am I calculating?
RANK()
ROW_NUMBER()
DENSE_RANK()
SUM()
AVG()
LAG()
LEAD()
Question 2 — Should I divide into groups?

If yes:

PARTITION BY team

If no, leave it out.

Question 3 — In what order?
ORDER BY calls_handled DESC

For ranking:

PARTITION BY → Who should compete together?

ORDER BY → What determines their position?

Exercises

1. Rank all records based on calls handled.
2. Use ROW_NUMBER() to number records from highest to lowest calls.
3. Use RANK() to rank records.
4. Use DENSE_RANK() to rank records.
5. Compare the results of all three ranking functions.
6. Rank agents separately within each team.
7. Rank records according to customer rating.
8. Find the top 3 performance records in each team.
9. Find each agent's best performance day.
10. Rank agents based on their total calls handled.*/
SELECT
    call_id,
    agent_name,
    team,
    calls_handled,
    RANK() OVER(
        ORDER BY calls_handled DESC
    ) AS call_rank
FROM call_performance;

SELECT
    call_id,
    agent_name,
    calls_handled,
    ROW_NUMBER() OVER(
        ORDER BY calls_handled DESC
    ) AS row_num
FROM call_performance;

SELECT
    call_id,
    agent_name,
    calls_handled,
    RANK() OVER(
        ORDER BY calls_handled DESC
    ) AS rank_num
FROM call_performance;

SELECT
    call_id,
    agent_name,
    calls_handled,
    DENSE_RANK() OVER(
        ORDER BY calls_handled DESC
    ) AS dense_rank_num
FROM call_performance;

SELECT
    call_id,
    agent_name,
    calls_handled,
    ROW_NUMBER() OVER(
        ORDER BY calls_handled DESC
    ) AS row_number_rank,
    RANK() OVER(
        ORDER BY calls_handled DESC
    ) AS rank_num,
    DENSE_RANK() OVER(
        ORDER BY calls_handled DESC
    ) AS dense_rank_num
FROM call_performance;

SELECT
    call_id,
    agent_name,
    team,
    calls_handled,
    RANK() OVER(
        PARTITION BY team
        ORDER BY calls_handled DESC
    ) AS team_rank
FROM call_performance;

SELECT
    call_id,
    agent_name,
    team,
    customer_rating,
    RANK() OVER(
        ORDER BY customer_rating DESC
    ) AS rating_rank
FROM call_performance;

SELECT *
FROM (
    SELECT
        call_id,
        agent_name,
        team,
        calls_handled,
        customer_rating,
        RANK() OVER(
            PARTITION BY team
            ORDER BY calls_handled DESC
        ) AS team_rank
    FROM call_performance
) AS ranked
WHERE team_rank <= 3;

SELECT
    agent_name,
    performance_date,
    calls_handled
FROM (
    SELECT
        agent_name,
        performance_date,
        calls_handled,
        ROW_NUMBER() OVER(
            PARTITION BY agent_name
            ORDER BY calls_handled DESC
        ) AS rn
    FROM call_performance
) AS ranked
WHERE rn = 1;

SELECT
    agent_name,
    SUM(calls_handled) AS total_calls,
    RANK() OVER(
        ORDER BY SUM(calls_handled) DESC
    ) AS agent_rank
FROM call_performance
GROUP BY agent_name;

-- Practice Set 8 — CTE + Correlated Subqueries

-- Scenario: Insurance Claims

CREATE TABLE insurance_claims (
claim_id INT PRIMARY KEY,
customer_name VARCHAR(100),
insurance_type VARCHAR(50),
claim_amount DECIMAL(12,2),
branch VARCHAR(50)
);
INSERT INTO insurance_claims VALUES
(1, 'Ajay Kumar', 'Health', 75000, 'Hyderabad'),
(2, 'Meena Shah', 'Motor', 45000, 'Mumbai'),
(3, 'Rohit Jain', 'Health', 125000, 'Hyderabad'),

(4, 'Sara Ali', 'Travel', 30000, 'Delhi'),
(5, 'Vikas Rao', 'Motor', 85000, 'Mumbai'),
(6, 'Nisha Singh', 'Health', 60000, 'Delhi'),
(7, 'Imran Khan', 'Travel', 55000, 'Hyderabad'),
(8, 'Pooja Patel', 'Motor', 40000, 'Delhi'),
(9, 'Karan Mehta', 'Health', 150000, 'Mumbai'),
(10, 'Farah Ahmed', 'Travel', 35000, 'Hyderabad');

/*
CTE (WITH) → create a temporary named result and use it in the main query.
Correlated subquery → a subquery that depends on the current row of the outer query.
1. CTE — Common Table Expression

A CTE is basically a temporary result set with a name.
Instead of writing one huge query like:

Calculate totals → filter them → rank them → display them

you can break the work into steps:

Step 1 → CTE
Step 2 → Main query

The basic syntax is:

WITH cte_name AS (
    SELECT ...
)
SELECT ...
FROM cte_name;
The biggest advantage is readability.
CTE is NOT a permanent table
For example:

WITH claim_totals AS (
    SELECT
        insurance_type,
        SUM(claim_amount) AS total_claim
    FROM insurance_claims
    GROUP BY insurance_type
)
SELECT
    insurance_type,
    total_claim
FROM claim_totals
WHERE total_claim > 200000;

Now each part has a clear purpose.
CTE with average

Suppose the business asks:

"Find claims that are above the overall average claim amount."

First calculate the average:

SELECT AVG(claim_amount)
FROM insurance_claims;

You could put that into a CTE:

WITH average_claim AS (
    SELECT AVG(claim_amount) AS avg_amount
    FROM insurance_claims
)
SELECT *
FROM insurance_claims
WHERE claim_amount > (
    SELECT avg_amount
    FROM average_claim
);
You can create more than one CTE.

For example:

WITH type_totals AS (
    SELECT
        insurance_type,
        SUM(claim_amount) AS total_claim
    FROM insurance_claims
    GROUP BY insurance_type
),
branch_totals AS (
    SELECT
        branch,
        SUM(claim_amount) AS total_claim
    FROM insurance_claims
    GROUP BY branch
)
SELECT ...

Notice the comma:

correlated subquery

Requirement:

Find claims greater than the average claim amount for their own insurance type.

Pattern:

SELECT *
FROM insurance_claims ic
WHERE claim_amount > (
    SELECT AVG(ic2.claim_amount)
    FROM insurance_claims ic2
    WHERE ic2.insurance_type = ic.insurance_type
);

Notice:

ic2.insurance_type = ic.insurance_type

This is the heart of the correlated subquery.
How to identify which technique to use

When you read an SQL question, look for these words.

CTE clues

If the question says:

"Create a temporary result..."

"Calculate X, then use that result..."

"Create two intermediate results..."

Think:

WITH ...
Correlated subquery clues

If the question says:

"for their own department"

"within their own branch"

"compared to others in the same category"

"greater than the average for its group"



CTE Exercises

1. Create a CTE calculating total claims by insurance type.
2. Use a CTE to calculate total claims by branch.
3. Find insurance types whose total claim amount exceeds ₹2,00,000.
4. Create a CTE calculating average claim amount and filter claims above that average.
5. Create a CTE and rank insurance types by total claim amount.
6. Create two CTEs in the same query and combine their results.
Correlated Subquery Exercises
7. Find claims greater than the average claim amount for their own insurance type.
8. Find claims greater than the average claim amount at their own branch.
9. Find the largest claim for each insurance type.
10. Find customers whose claim is above the branch average.
*/

WITH claim_totals AS (
    SELECT
        insurance_type,
        SUM(claim_amount) AS total_claim
    FROM insurance_claims
    GROUP BY insurance_type
)
SELECT *
FROM claim_totals;


WITH branch_totals AS (
    SELECT
        branch,
        SUM(claim_amount) AS total_claim
    FROM insurance_claims
    GROUP BY branch
)
SELECT *
FROM branch_totals;

WITH claim_totals AS (
    SELECT
        insurance_type,
        SUM(claim_amount) AS total_claim
    FROM insurance_claims
    GROUP BY insurance_type
)
SELECT *
FROM claim_totals
WHERE total_claim > 200000;


WITH average_claim AS (
    SELECT
        AVG(claim_amount) AS avg_claim
    FROM insurance_claims
)
SELECT *
FROM insurance_claims
WHERE claim_amount > (
    SELECT avg_claim
    FROM average_claim
);


WITH claim_totals AS (
    SELECT
        insurance_type,
        SUM(claim_amount) AS total_claim
    FROM insurance_claims
    GROUP BY insurance_type
)
SELECT
    insurance_type,
    total_claim,
    RANK() OVER(
        ORDER BY total_claim DESC
    ) AS claim_rank
FROM claim_totals;


WITH type_totals AS (
    SELECT
        insurance_type,
        SUM(claim_amount) AS total_claim
    FROM insurance_claims
    GROUP BY insurance_type
),
branch_totals AS (
    SELECT
        branch,
        SUM(claim_amount) AS total_claim
    FROM insurance_claims
    GROUP BY branch
)
SELECT
    type_totals.insurance_type,
    type_totals.total_claim AS type_total,
    branch_totals.branch,
    branch_totals.total_claim AS branch_total
FROM type_totals
CROSS JOIN branch_totals;

SELECT *
FROM insurance_claims ic
WHERE claim_amount > (
    SELECT AVG(ic2.claim_amount)
    FROM insurance_claims ic2
    WHERE ic2.insurance_type = ic.insurance_type
);


SELECT *
FROM insurance_claims ic
WHERE claim_amount > (
    SELECT AVG(ic2.claim_amount)
    FROM insurance_claims ic2
    WHERE ic2.branch = ic.branch
);


SELECT *
FROM insurance_claims ic
WHERE claim_amount = (
    SELECT MAX(ic2.claim_amount)
    FROM insurance_claims ic2
    WHERE ic2.insurance_type = ic.insurance_type
);


SELECT
    customer_name,
    claim_amount,
    branch
FROM insurance_claims ic
WHERE claim_amount > (
    SELECT AVG(ic2.claim_amount)
    FROM insurance_claims ic2
    WHERE ic2.branch = ic.branch
);

-- Practice Set 9 — Hierarchical Queries

-- Scenario: Company Reporting Structure

CREATE TABLE staff_hierarchy (
employee_id INT PRIMARY KEY,
employee_name VARCHAR(100),
manager_id INT,
designation VARCHAR(100)
);
INSERT INTO staff_hierarchy VALUES
(1, 'Raj Malhotra', NULL, 'CEO'),
(2, 'Meera Shah', 1, 'CTO'),
(3, 'Vikram Rao', 1, 'Sales Director'),

(4, 'Aman Khan', 2, 'Engineering Manager'),
(5, 'Sara Ali', 2, 'Data Manager'),
(6, 'Rohit Das', 4, 'Developer'),
(7, 'Priya Singh', 4, 'Developer'),
(8, 'Kabir Ahmed', 5, 'Data Engineer'),
(9, 'Neha Rao', 5, 'Data Analyst'),
(10, 'Imran Sheikh', 3, 'Sales Manager'),
(11, 'Pooja Jain', 10, 'Sales Executive');

/*
WITH RECURSIVE hierarchy AS (

    -- Anchor
    SELECT ...
    FROM staff_hierarchy
    WHERE employee_id = <starting employee>

    UNION ALL

    -- Recursive
    SELECT ...
    FROM staff_hierarchy s
    JOIN hierarchy h
        ON s.manager_id = h.employee_id
)

SELECT *
FROM hierarchy;

Then change only the starting condition.

Exercises

1. Find employees having no manager.
2. Find direct reports of the CEO.
3. Find direct reports of the CTO.
4. Use a recursive CTE to display the complete hierarchy.
5. Add a hierarchy level to the result.
6. Find all employees working below Meera Shah .
7. Find everyone working below Aman Khan .
8. Display employee → manager relationships.
9. Determine how many employees are at each hierarchy level.
10. Display the organization starting with CEO and recursively moving downward.*/

SELECT *
FROM staff_hierarchy
WHERE manager_id IS NULL;

SELECT *
FROM staff_hierarchy
WHERE manager_id = (
    SELECT employee_id
    FROM staff_hierarchy
    WHERE designation = 'CEO'
);

SELECT *
FROM staff_hierarchy
WHERE manager_id = (
    SELECT employee_id
    FROM staff_hierarchy
    WHERE designation = 'CTO'
);

WITH RECURSIVE hierarchy AS (
    SELECT
        employee_id,
        employee_name,
        manager_id,
        designation
    FROM staff_hierarchy
    WHERE manager_id IS NULL

    UNION ALL

    SELECT
        s.employee_id,
        s.employee_name,
        s.manager_id,
        s.designation
    FROM staff_hierarchy s
    JOIN hierarchy h
        ON s.manager_id = h.employee_id
)
SELECT *
FROM hierarchy;

WITH RECURSIVE hierarchy AS (
    SELECT
        employee_id,
        employee_name,
        manager_id,
        designation,
        0 AS hierarchy_level
    FROM staff_hierarchy
    WHERE manager_id IS NULL

    UNION ALL

    SELECT
        s.employee_id,
        s.employee_name,
        s.manager_id,
        s.designation,
        h.hierarchy_level + 1
    FROM staff_hierarchy s
    JOIN hierarchy h
        ON s.manager_id = h.employee_id
)
SELECT *
FROM hierarchy
ORDER BY hierarchy_level, employee_id;

WITH RECURSIVE hierarchy AS (
    SELECT
        employee_id,
        employee_name,
        manager_id,
        designation
    FROM staff_hierarchy
    WHERE employee_name = 'Meera Shah'

    UNION ALL

    SELECT
        s.employee_id,
        s.employee_name,
        s.manager_id,
        s.designation
    FROM staff_hierarchy s
    JOIN hierarchy h
        ON s.manager_id = h.employee_id
)
SELECT *
FROM hierarchy
WHERE employee_name <> 'Meera Shah';

WITH RECURSIVE hierarchy AS (
    SELECT
        employee_id,
        employee_name,
        manager_id,
        designation
    FROM staff_hierarchy
    WHERE employee_name = 'Aman Khan'

    UNION ALL

    SELECT
        s.employee_id,
        s.employee_name,
        s.manager_id,
        s.designation
    FROM staff_hierarchy s
    JOIN hierarchy h
        ON s.manager_id = h.employee_id
)
SELECT *
FROM hierarchy
WHERE employee_name <> 'Aman Khan';

SELECT
    e.employee_name AS employee,
    m.employee_name AS manager
FROM staff_hierarchy e
LEFT JOIN staff_hierarchy m
    ON e.manager_id = m.employee_id;
    

WITH RECURSIVE hierarchy AS (
    SELECT
        employee_id,
        manager_id,
        0 AS hierarchy_level
    FROM staff_hierarchy
    WHERE manager_id IS NULL

    UNION ALL

    SELECT
        s.employee_id,
        s.manager_id,
        h.hierarchy_level + 1
    FROM staff_hierarchy s
    JOIN hierarchy h
        ON s.manager_id = h.employee_id
)
SELECT
    hierarchy_level,
    COUNT(*) AS employee_count
FROM hierarchy
GROUP BY hierarchy_level
ORDER BY hierarchy_level;

WITH RECURSIVE hierarchy AS (
    SELECT
        employee_id,
        employee_name,
        manager_id,
        designation,
        0 AS hierarchy_level,
        employee_name AS reporting_path
    FROM staff_hierarchy
    WHERE designation = 'CEO'

    UNION ALL

    SELECT
        s.employee_id,
        s.employee_name,
        s.manager_id,
        s.designation,
        h.hierarchy_level + 1,
        CONCAT(h.reporting_path, ' → ', s.employee_name)
    FROM staff_hierarchy s
    JOIN hierarchy h
        ON s.manager_id = h.employee_id
)
SELECT
    hierarchy_level,
    employee_name,
    designation,
    reporting_path
FROM hierarchy
ORDER BY reporting_path;



-- Practice Set 10 — GROUP BY Extensions /ROLLUP

-- Scenario: Hotel Revenue

CREATE TABLE hotel_bookings (
booking_id INT PRIMARY KEY,
hotel_city VARCHAR(50),
room_type VARCHAR(50),
nights INT,
amount DECIMAL(10,2)
);
INSERT INTO hotel_bookings VALUES
(1, 'Hyderabad', 'Standard', 2, 6000),

(2, 'Hyderabad', 'Deluxe', 3, 13500),
(3, 'Hyderabad', 'Suite', 2, 18000),
(4, 'Mumbai', 'Standard', 2, 9000),
(5, 'Mumbai', 'Deluxe', 3, 18000),
(6, 'Mumbai', 'Suite', 1, 15000),
(7, 'Bangalore', 'Standard', 3, 10500),
(8, 'Bangalore', 'Deluxe', 2, 12000),
(9, 'Bangalore', 'Suite', 2, 20000);

/*Exercises

1. Find total revenue by city.
2. Find total revenue by room type.
3. Group by city and room type.
4. Produce city-wise subtotals using WITH ROLLUP .
5. Produce a grand total.
6. Calculate total nights by city and room type.
7. Display subtotals and overall totals in the same result.*/

SELECT
    hotel_city,
    SUM(amount) AS total_revenue
FROM hotel_bookings
GROUP BY hotel_city;

SELECT
    room_type,
    SUM(amount) AS total_revenue
FROM hotel_bookings
GROUP BY room_type;

SELECT
    hotel_city,
    room_type,
    SUM(amount) AS total_revenue
FROM hotel_bookings
GROUP BY hotel_city, room_type;

SELECT
    hotel_city,
    room_type,
    SUM(amount) AS total_revenue
FROM hotel_bookings
GROUP BY hotel_city, room_type WITH ROLLUP;

SELECT
    SUM(amount) AS grand_total
FROM hotel_bookings;

SELECT
    hotel_city,
    room_type,
    SUM(nights) AS total_nights
FROM hotel_bookings
GROUP BY hotel_city, room_type;

SELECT
    hotel_city,
    room_type,
    SUM(amount) AS total_revenue,
    SUM(nights) AS total_nights
FROM hotel_bookings
GROUP BY hotel_city, room_type WITH ROLLUP;
